In [ ]:
import math
def basic_sigmoid(x):
  s=1/(1+math.exp(-x))
  return s



In [ ]:
basic_sigmoid(-1)

0.2689414213699951

vector

In [ ]:
import numpy as np
x=np.array([1,2,3])
print(np.exp(x))

[ 2.71828183  7.3890561  20.08553692]


In [ ]:
x= np.array([1,2,3])
print(x+3)

[4 5 6]


In [ ]:
basic_sigmoid(x)

array([0.73105858, 0.88079708, 0.95257413])

numpy instead of math

In [ ]:
import math
def basic_sigmoid(x):
  s=1/(1+np.exp(-x))
  return s
basic_sigmoid(-1)

0.2689414213699951

sigmoid gradient

In [ ]:
def sigmoid_derivative(x):
  s=1/(1+np.exp(-x))
  ds=s*(1-s)
  return ds
  return ds

In [ ]:
x=np.array([1,2,3])
print("sigmoid_derivative(x)="+str(sigmoid_derivative(x)))

sigmoid_derivative(x)=[0.19661193 0.10499359 0.04517666]


Reshaping arrays

In [ ]:
def image2vector(image):
  v=image.reshape((image.shape[0]*image.shape[1]*image.shape[2],1))
  return v

In [ ]:
image=np.array([[[0.67826139,0.29380381],[0.90714982,0.52835647],[0.4215251,0.45017551]],
                [[0.92814219,0.96677647],[0.85304703,0.52351845],[0.19981397,0.27417313]],
                [[0.60659855,0.00533165],[0.10820313,0.499789337],[0.34144279,0.94630077]]])
print("image2vector(image)="+str(image2vector(image)))

image2vector(image)=[[0.67826139]
 [0.29380381]
 [0.90714982]
 [0.52835647]
 [0.4215251 ]
 [0.45017551]
 [0.92814219]
 [0.96677647]
 [0.85304703]
 [0.52351845]
 [0.19981397]
 [0.27417313]
 [0.60659855]
 [0.00533165]
 [0.10820313]
 [0.49978934]
 [0.34144279]
 [0.94630077]]


normalising rows

In [ ]:
def normalizeRows(x):
  x_norm=np.linalg.norm(x,axis=1,keepdims=True)
  x=x/x_norm
  return x

In [ ]:
x=np.array([[0,1000,4],[2,6,4]])
print("normalizeRows(x)="+str(normalizeRows(x)))

normalizeRows(x)=[[0.         0.999992   0.00399997]
 [0.26726124 0.80178373 0.53452248]]


Broadcasting and softmax function

In [ ]:
def softmax(x):
  x_exp=np.exp(x)
  x_sum=np.sum(x_exp,axis=1,keepdims=True)
  s=x_exp/x_sum
  return s

In [ ]:
x=np.array([[9,2,5,0,0],[7,5,0,0,0]])
print("softmax(x)="+str(softmax(x)))

softmax(x)=[[9.80897665e-01 8.94462891e-04 1.79657674e-02 1.21052389e-04
  1.21052389e-04]
 [8.78679856e-01 1.18916387e-01 8.01252314e-04 8.01252314e-04
  8.01252314e-04]]


Vectorization

In [28]:
import time
x1=[9,2,5,0,0,7,5,0,0,0,9,2,5,0,0]
x2=[9,2,2,9,0,9,2,5,0,0,9,2,5,0,0]
tic=time.process_time()
dot=0
for i in range(len(x1)):
  dot+=x1[i]*x2[i]
toc=time.process_time()
print("dot="+str(dot)+"---computation time="+str(1000*(toc-tic))+"ms")




dot=278---computation time=0.1766210000013757ms


In [29]:
x1=[9,2,5,0,0,7,5,0,0,0,9,2,5,0,0]
x2=[9,2,2,9,0,9,2,5,0,0,9,2,5,0,0]

#vextorized dot product
tic=time.process_time()
dot=np.dot(x1,x2)
toc=time.process_time()
print("dot="+str(dot)+"---computation time="+str(1000*(toc-tic))+"ms")


dot=278---computation time=0.25090000000105306ms


implement l1 and l2 loss function

In [ ]:
def L1(yhat,y):
  loss=np.sum(np.abs(y-yhat))
  return loss

In [ ]:
yhat=np.array([1,1,1,1,1])
y=np.array([1,1,1,1,1])
print("L1="+str(L1(yhat,y)))

L1=0


In [ ]:

#classic outer product implementation
tic=time.process_time()
outer=np.zeros((len(x1),len(x2)))
for i in range(len(x1)):
  for j in range(len(x2)):
    outer[i,j]=x1[i]*x2[j]
    toc=time.process_time()
print("outer="+str(outer)+"---computation time="+str(1000*(toc-tic))+"ms")
#classic elementwise implementation
tic=time.process_time()
mul=np.zeros(len(x1))
for i in range(len(x1)):
  mul[i]=x1[i]*x2[i]
  toc=time.process_time()
  print("mul="+str(mul)+"---computation time="+str(1000*(toc-tic))+"ms")

In [ ]:
#vexorized outer product
tic=time.process_time()
outer=np.outer(x1,x2)
toc=time.process_time()
print("outer="+str(outer)+"---computation time="+str(1000*(toc-tic))+"ms")
#vectorized elementwise multiplication
tic=time.process_time()
mul=np.multiply(x1,x2)
toc=time.process_time()
print("mul="+str(mul)+"---computation time="+str(1000*(toc-tic))+"ms")